Update Lithium support
Noaaan/MythicMetalsDecorations pull request #26
Opened 2024-12-20 16:50 UTC by muon-rw

hey metalsguy. 

This PR:
- Updates Lithium to the latest modrinth release, and all other required deps for such (can be seen in commit notes - this includes a change to 1.21.1, so you may want to move this to a different branch.)
- Updates imports for Lithium to the net.caffeinemc package
- Adds the missing method override for `setInventoryLithium`, necessary for proper interaction with Lithium optimized hoppers.
*Note*: This would have also been broken on previous versions as far as I can tell; it's not a newly added method on Lithium's end. I'm not sure if maybe this was excluded for a good reason, but this implementation seems to work fine in all cases.

2025-01-01 23:48 UTC, Noaaan requested changes
Looks good. I think shadowing the field over the method is better. If required, changing the field to `protected` is fine.

2025-01-01 23:48 UTC, Noaaan commented on src/main/java/nourl/mythicmetalsdecorations/mixin/MythicChestBlockEntityLithiumCompatMixin.java
> +        // hi mom
I haven't seen a method shadow like this. This won't cause any jank, would it?
Ideally this should just shadow the `inventory` field instead, with the setter actually just setting the inventory.

2025-01-02 00:53 UTC, muon-rw commented on src/main/java/nourl/mythicmetalsdecorations/mixin/MythicChestBlockEntityLithiumCompatMixin.java
> +        // hi mom
This [old page on the Fabric Wiki](https://wiki.fabricmc.net/tutorial:mixin_tips) mentions it as valid, though I suppose shadowing the field in this case is just a tiny bit cleaner. 

Changed. (The remap=false is necessary for the shadow target outside of dev)

2025-01-02 00:59 UTC, Noaaan approved these changes
Will have this merged + released hopefully by tomorrow

2025-01-02 17:24 UTC, merged